### ISSUE TITLE
Homey temperature 

### ISSUE THREAD

**Issue by felho001** [balmli/com.sensibo#11]
Hi after install homey sensibo app work fine but 1 smttings not work i can't settings temperature ring. Can you fix this?

**Comment by balmli** [comment]
Hi,

Can you please explain a bit more what's the issue ?

**Comment by felho001** [comment]
Oh I was stupid because if I didn't touch the line. drags the screen. sorry

**Comment by felho001** [comment]
![IMG_0029](https://user-images.githubusercontent.com/45117257/116579615-d865fc80-a912-11eb-9850-5f2a0c162f67.jpg)
