### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by m4xx75** [balmli/com.sensibo#15]
Is it possible to add a card allowing ON/OFF the air conditioning light.
This is an option available natively in Sensibo:

![Screenshot_20210616-002938_Sensibo.jpg](https://user-images.githubusercontent.com/31291478/122131766-f7c0d680-ce39-11eb-921d-d34fa6f55559.jpg)

Thanks !

**Comment by balmli** [comment]
I don't think that is supported by the Sensibo API
https://sensibo.github.io/

But if it is, it can be added of course.
