### ISSUE TITLE
Sensibo Air + Room Sensor 

### ISSUE THREAD

**Issue by bnorheim** [balmli/com.sensibo#17]
I have a Sensibo Air + Room Sensor but I can´t use the room sensor within Homey. The only option I got is the main unit. Are there any plans for supporting this in the near future?

Thanks,
bnorheim

**Comment by balmli** [comment]
The room sensor is not supported by the Sensibo Api, so not for now.

Here's a link to the documentation for the API, https://sensibo.github.io/

I guess you can contact Sensibo, and ask them to update the API for that.

**Comment by victornedstrom** [comment]
This is no longer the case, as both Tibber and Home Assistant support using the room sensor as primary sensor (i.e. it mirrors the setting from the Sensibo app). See e.g. https://github.com/home-assistant/core/issues/63064 

I suggest this issue is re-opened!
