### ISSUE TITLE
Cannot add Sensibo in Homey

### ISSUE THREAD

**Issue by SmartAmateur** [balmli/com.sensibo#18]
Hi,
After creating an API-key in https://home.sensibo.com/me/api I try to add my Sensibo device in Homey - but all I get is the message "The API-key must be configured.". All I can do here is to click "Close". Any suggestions what to do? Thanks!

**Comment by balmli** [comment]
Have you read the instructions on top of this page ?
https://community.athom.com/t/app-sensibo/28990

**Comment by SmartAmateur** [comment]
Hei Bjørnar and thank you for your quick response!
Yes, I have read the instructions. Two API-keys were created before I tried
to install the app on my Homey.

Question: could it be an issue that I have the mobile app installed as well?

Thanks!

Wbr
Piero

ons. 8. sep. 2021 kl. 08:39 skrev Bjørnar Almli ***@***.***>:

**Comment by balmli** [comment]
You can use the community page to get support.  Other users might be able to help

https://community.athom.com/t/app-samsung-smarttv/10019
