### ISSUE TITLE
Not working in Homey 2.0

### ISSUE THREAD

**Issue by BuSHari** [balmli/com.sensibo#2]
Hello, 
Thanks for the app for Homey.
Unfortunately this app is not working well with the Homey 2.0.
We can’t turn on/off the device and can’t know the state of the device.

Thanks,
Idan

**Comment by balmli** [comment]
Hi, 

Have you reinstalled the app after upgrading to 2.0 ?

**Comment by BuSHari** [comment]
Yes, I never installed it before 2.0

**Comment by balmli** [comment]
Can you check that you have set the key correctly in the configure screen ?

If it still doesn't work, you can press the "Create diagnostics report", and I will get an email with the log.

**Comment by BuSHari** [comment]
Yes, I’ve set the key correctly because I cN see some parameters.
I’ll send you the diagnostic report.

Thanks

**Comment by BuSHari** [comment]
I didn’t saw a “Creat diagnostics report” in the app settings, I can see it only in the General settings of Homey, that only Athom employees can see.

**Comment by balmli** [comment]
Thanks,  The logs seems to be good.

Can you try to turn on / off, change the target temperature etc, and press the diagnostics button again ?

**Comment by BuSHari** [comment]
Here is the new log id:
8f161a59-735e-46b7-9406-928af657a215

**Comment by balmli** [comment]
I can see that you tried to change the target temp to 23, and then 20.

Can you create a flow to turn the AC on ?   The "Turn on" action.

**Comment by BuSHari** [comment]
Its working with a flow, but i cant turn it on or off and the current state from the device section

**Comment by balmli** [comment]
To understand:  You can turn it on / off with the flow ?  So that works for you? 

But "from the device section", you mean from the mobile app ?

**Comment by BuSHari** [comment]
Yes, from Homey 2.0, the only option is from mobile device

**Comment by balmli** [comment]
You can turn on/off, set the more and set the fan level from a flow.

And you can set the target temperature from the mobile app.

Sorry for asking again, but is it only changing the target temperature from the mobile app that does not wokr ?

**Comment by BuSHari** [comment]
I want to turn it on/off and check it state from the mobile using Homey, but not through flows.
Right now i can only change the temperature

**Comment by balmli** [comment]
I see.  Well, that's not supported but the app.

But you can add a virtual device button to start a flow that turns the AC on / off.  You'll have to add the Virtual devices app, add a virtual button and then add a flow that triggers when the button is pressed.

**Comment by BuSHari** [comment]
Homey 2.0 app does support it, I have other apps that do it.
