### ISSUE TITLE
Any chance to control it from device screen?

### ISSUE THREAD

**Issue by BuSHari** [balmli/com.sensibo#3]
Hello,

Right now the app is working great under the Flows, 
But i want to control the AC manually from Homey device screen, so i will be able also to connect it to Homekit to controll it from siri or Google Assistant.

So, is it possible for you to add those actions to device screen?

Thanks,
Idan

**Comment by balmli** [comment]
Hi Idan,

I will try to support this.


Best regards
Bjørnar

**Comment by BuSHari** [comment]
Thank you very much!

**Comment by aeklo** [comment]
My heat pump shows up in HomeKit with current version of Sensibo app, but the controls does not work as expected.
I have modes “OFF”, “HEAT”, “COOL” and “AUTO”.
By selecting OFF when running, the pump shuts down ok. But, when selecting “HEAT”, it starts up and shuts down again within 1 sec (two commands sent). Guess this could be a combination of app and HomeKit, but I would gladly assist in debugging this one :)

**Comment by balmli** [comment]
Hi,

Need alpha-testers for this... since I do not have a Sensibo myself.. :-)

Please send your email you use for Athom to me (bjornar.almli@gmail.com), and I will add you to the list of alpha-testers.

**Comment by BuSHari** [comment]
Thank you,

Ive sent you an email...

**Comment by balmli** [comment]
Just updated app store with v. 0.3.1 -- alpha version.

**Comment by balmli** [comment]
v. 0.4.0 uploaded as beta, waiting for approval.

**Comment by balmli** [comment]
v. 0.4.0 is now ready in app store
