### ISSUE TITLE
The app sometimes doesn’t recognize state

### ISSUE THREAD

**Issue by BuSHari** [balmli/com.sensibo#4]
Hello,

I’m using the latest Beta version, sometimes when I turn on the device trough the official app the Sensibo Homey app doesn’t recognize the state of the device.

Here is my diagnostic report code: 
6dcea574-d413-40fa-a7e7-d282cff8742b

Thanks,
Idan

**Comment by balmli** [comment]
Hi,

The Sensibo app pulls the state from the Sensibo sky interface on the net.  Every minute.

So there are a lot of different things that can happen, like your Internet connection etc..

Not much I can do.

**Comment by BuSHari** [comment]
There is no issue with my internet connection.
i've made a GET request to my sensibo and i can see that my AC is on, but the Sensibo homey app isnt recognize it.
