### ISSUE TITLE
"Dry" mode missing

### ISSUE THREAD

**Issue by Alextoh76** [balmli/com.sensibo#7]
Hi,

My remote has the "Dry" mode which is present in sensibo app but not in homey app.

See attached pics.

Hope to see it avail in homey app

Thx
![Screenshot_20201104-005244_Sensibo](https://user-images.githubusercontent.com/17327829/98024054-b8adba00-1e42-11eb-9f0e-40dc27f4050d.jpg)
![Screenshot_20201104-005229_Sensibo](https://user-images.githubusercontent.com/17327829/98024062-ba777d80-1e42-11eb-9533-64eb6e47a20f.jpg)
![Screenshot_20201104-005310_Homey](https://user-images.githubusercontent.com/17327829/98024069-bb101400-1e42-11eb-92b2-c7ce830dbc49.jpg)

**Comment by tobiasehlert** [comment]
Yeah that would be awesome! :-)

**Comment by tobiasehlert** [comment]
@Alextoh76, looks like there is support for **dry**-mode actually.
I was at least able to use that in my Homey Flow

https://github.com/balmli/com.sensibo/blob/85c206b2a3bfc0d4db943b391c38358a3666d813/drivers/Sensibo/device.js#L338
